const recipeSeeds = [
  { name: 'Beef Stroganoff Sauce with Meatballs',
    description: 'Classic beef stroganoff sauce with meatballs. Serve over rice or egg noodles.',
    tags: ['Pasta', 'Beef'],
    time: { hour: 1 },
    ingredients: [
      { amount: 0.5, unit: 'tsp', name: 'Vegetable oil' },
      { amount: 1, unit: 'pound', name: 'Ground sirloin' },
      { amount: 3, unit: 'tbsp', name: 'Worcestershire sauce' },
      { amount: 1, name: 'Egg' },
      { amount: 0.3, unit: 'cup', name: 'Dry bread crumbs' },
      { amount: 0.5, name: 'Small onions, chopped' },
      { amount: 0.25, unit: 'cup', name: 'Butter, divided' },
      { amount: 1, unit: 'pack', name: 'Mushrooms, sliced' },
      { amount: 2, unit: 'tbsp', name: 'All-purpose flour' },
      { amount: 1, unit: 'can', name: 'Beef broth' },
      { amount: 1, unit: 'tsp', name: 'Ground mustard' },
      { amount: 0.3, unit: 'cup', name: 'Sour cream' },
    ],
    steps: [
      { title: 'Step 1', body: 'Preheat the oven to 350 degrees F (175 degrees C). Coat a baking sheet with oil.' },
      { title: 'Step 2', body: 'Combine ground sirloin, Worcestershire sauce, egg, bread crumbs, onion, salt, and pepper in a bowl. Mix well. Divide into golf ball-sized meatballs. Place on the prepared baking sheet.' },
      { title: 'Step 3', body: 'Bake in the preheated oven until meatballs are no longer pink in the center, about 15 minutes.' },
      { title: 'Step 4', body: 'Melt 2 tablespoons butter in a large skillet over medium heat. Add mushrooms; cook and stir until soft, about 10 minutes. Push mushrooms to the side of the pan.' },
      { title: 'Step 5', body: 'Melt remaining 2 tablespoons butter in the skillet; whisk in flour. Add broth and mustard; bring to a boil. Add meatballs and cook until some sauce is absorbed, 10 to 15 minutes. Remove from heat. Add sour cream and stir to combine.' },
    ],
    owner: '618522305262bfd83fe2c6f3',
  }, { 
    name: 'Easy carrot cake',
    description: 'Top this classic carrot cake with moreish icing and chopped walnuts or pecans. Serve as a sweet treat with a cup of tea any time of the day.',
    tags: ['Desert', 'Cake', 'Carrot'],
    time: { hour: 1, minutes: 5 },
    ingredients: [
      { amount: 230, unit: 'ml', name: 'Vegetable oil' },
      { amount: 100, unit: 'g', name: 'Yogurt' },
      { amount: 4, name: 'Eggs' },
      { amount: 1.5, unit: 'tsp', name: 'Vanilla extract' },
      { amount: .5, name: 'Orange, zested' },
      { amount: 265, unit: 'g', name: 'Self-raising flour' },
      { amount: 335, unit: 'g', name: 'Light muscovado sugar' },
      { amount: 2.5, unit: 'tsp', name: 'Ground cinnamon' },
      { amount: .25, name: 'Fresh nutmeg, finely grated' },
      { amount: 265, unit: 'g', name: 'Carrots, grated' },
      { amount: 100, unit: 'g', name: 'Raisins' },
      { amount: 100, unit: 'g', name: 'Walnuts or pecans, roughly chopped (optional)' },
      { amount: 100, unit: 'g', name: 'Slightly salted butter, softened' },
      { amount: 200, unit: 'g', name: 'Icing sugar' },
      { amount: 100, unit: 'g', name: 'Soft cheese' },
    ],
    steps: [
      { title: 'Step 1', body: 'Heat the oven to 180C/160C fan/gas 4. Oil and line the base and sides of two 20cm cake tins with baking parchment. Whisk the oil, yogurt, eggs, vanilla and zest in a jug. Mix the flour, sugar, cinnamon and nutmeg with a good pinch of salt in a bowl. Squeeze any lumps of sugar through your fingers, shaking the bowl a few times to bring the lumps to the surface.' },
      { title: 'Step 2', body: 'Add the wet ingredients to the dry, along with the carrots, raisins and half the nuts, if using. Mix well to combine, then divide between the tins.' },
      { title: 'Step 3', body: 'Bake for 25-30 mins or until a skewer inserted into the centre of the cake comes out clean. If any wet mixture clings to the skewer, return to the oven for 5 mins, then check again. Leave to cool in the tins.' },
      { title: 'Step 4', body: 'To make the icing, beat the butter and sugar together until smooth. Add half the soft cheese and beat again, then add the rest (adding it bit by bit prevents the icing from splitting). Remove the cakes from the tins and sandwich together with half the icing. Top with the remaining icing and scatter with the remaining walnuts. Will keep in the fridge for up to five days. Best eaten at room temperature.' },
    ],
    owner: '618522305262bfd83fe2c6f3',
  }, { 
    name: 'Roast turkey',
    description: 'Take your Christmas turkey to the next level with our ultimate roast turkey and gravy. It doesn’t involve much extra work, yet tastes sensational',
    tags: ['Turkey', "Main", "Christmas"],
    time: { hour: 3, minutes: 30 },
    ingredients: [
      { amount: 5, unit: 'kg', name: 'oven-ready turkey' },
      { amount: 150, unit: 'g', name: 'butter' },
      { amount: 3, name: 'garlic cloves, finely grated' },
      { amount: 2, name: 'lemons, both halved, 1 juiced' },
      { amount: 1, name: 'onion, roughly chopped' },
      { amount: 2, name: 'carrots, roughly chopped' },
      { amount: 2, unit: 'tbsp', name: 'plain flour' },
      { amount: 1, unit: 'tbsp', name: 'soy sauce' },
      { amount: 1, unit: 'tsp', name: 'yeast extract' },
      { amount: 200, unit: 'ml', name: 'large glass of red wine' },
      { amount: 500, unit: 'ml', name: 'chicken or turkey stock' },
    ],
    steps: [
      { title: 'Step 1', body: 'Up to 48 hrs and at least 12 hrs before cooking, loosen the skin over the turkey breast so you can get your hands underneath it. Season the bird all over, including under the skin, with 2 tbsp sea salt. Put the turkey in a large roasting tin, breast-side up. Leave uncovered in the fridge until ready to cook.' },
      { title: 'Step 2', body: 'Remove the turkey from the fridge at least 1 hr before cooking. Heat the oven to 240C/220C fan/gas 9. Melt the butter in a pan set over a low heat, then add the garlic, chopped herbs and lemon juice. Sizzle for 1 min, remove from the heat and leave to cool a little. Remove the turkey from the tin and scatter in the onions, carrots, turkey neck and giblets. Put a roasting rack, trivet or ovenproof cooling rack in or over the tray and sit the turkey on top. Stuff the squeezed and whole lemons in the turkey cavity with the herb stalks and extra thyme. Lift the skin and spoon about 4 tbsp of the garlicky herb butter over the meat underneath, then massage the skin to spread it out. Brush most of the remaining butter all over the bird, reserving about 2 tbsp. For a neat finish, tie the wings and legs together.' },
      { title: 'Step 3', body: 'Put the turkey in the oven and reduce the heat to 180C/160C fan/gas 4. Roast for 1 hr, then remove from the oven and brush with more of the butter. Turn the tin around and return to the oven for another 30 mins. Brush again with the butter and roast for another 30 mins. After the turkey has had 2 hrs in total, check its temperature with a probe thermometer. It’s cooked perfectly when the thickest part of the breast reads about 65C and the thickest part of the thigh reads 75C. If the temperature is lower, return the turkey to the oven for periods of 15 mins until the temperature is reached. Cool for 10 mins on the rack, then transfer to a board and leave upside down – the turkey should rest for at least another 20 mins and will stay hot for at least 40 mins more.' },
      { title: 'Step 4', body: 'Meanwhile, make the gravy. If the roasting tin is flameproof, put it directly over a medium heat. If not, scrape the contents into a large, shallow pan. Scatter over the flour and stir to make a paste. Add the soy sauce and yeast extract, stir, then pour in the wine and combine to form a thick paste. Pour in the stock and turkey juices (if you aren’t already cooking them in the roasting tin). Simmer for about 5 mins, stirring to make a rich gravy. Strain into a jug or pan to reheat when needed.' },
      { title: 'Step 5', body: 'Put the turkey on a platter, then serve with the gravy and other trimmings of your choice.' },
    ],
    owner: '618522305262bfd83fe2c6f3',
  }, 
]

// { 
//   name: '',
//   description: '',
//   tags: [''],
//   time: { hour: '', minutes: '' },
//   ingredients: [
//     { amount: 1, unit: '', name: '' },
//   ],
//   steps: [
//     { title: '', body: '' },
//   ],
//   owner: '618522305262bfd83fe2c6f3',
// },

module.exports = recipeSeeds;